/**
 * Theme Patcher Tests
 *
 * Tests that verify the TypeScript port matches Python output exactly.
 * These tests use the firmware downloading infrastructure to compare outputs.
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { readFileSync } from 'node:fs';
import {
	ThemePatcher,
	encodeBl,
	encodeB16bit,
	encodeMovw,
	encodePush,
	discoverFlacFunction,
	discoverMenuFunction,
	findFunctionStart,
	NopSlideFinder,
	PatchDetector,
	crc16,
	type PatchResult,
	type PatchAnalysisResult,
	type NopSlide,
	type PatchPoint
} from '../theme/index.js';
import { ThumbDecoder, InstructionType } from '../theme/thumb/index.js';
import type { FirmwareFile } from '../extractors/batch-processor.js';
import { BatchProcessor } from '../extractors/batch-processor.js';
import { fileIO } from '../utils/file-io.js';

// Expected test results from Python (these should be generated by running Python)
interface PythonTestResult {
	version: string;
	flacColors: number[];
	menuColors: number[];
	patchPoints: {
		flac: { patchAddr: number; originalBytes: string; newBytes: string } | null;
		menu: { patchAddr: number; originalBytes: string; newBytes: string } | null;
	};
	nopSlide: { start: number; end: number; size: number };
	metadataAddr: number;
}

/**
 * Compare TypeScript result with Python reference
 */
function compareWithPython(
	tsResult: PatchResult,
	pythonResult: PythonTestResult
): void {
	// Compare FLAC colors
	expect(tsResult.nopSlide.start).toEqual(pythonResult.nopSlide.start);
	expect(tsResult.nopSlide.end).toEqual(pythonResult.nopSlide.end);
	expect(tsResult.nopSlide.size).toEqual(pythonResult.nopSlide.size);
	expect(tsResult.metadataAddr).toEqual(pythonResult.metadataAddr);

	// Compare patch points
	const flacPoint = tsResult.patchPoints['flac'];
	const menuPoint = tsResult.patchPoints['menu'];

	if (pythonResult.patchPoints.flac && flacPoint) {
		expect(flacPoint.patchAddr).toEqual(
			pythonResult.patchPoints.flac.patchAddr
		);
		expect(flacPoint.originalBytes).toEqual(
			pythonResult.patchPoints.flac.originalBytes
		);
		expect(flacPoint.newBytes).toEqual(
			pythonResult.patchPoints.flac.newBytes
		);
	}

	if (pythonResult.patchPoints.menu && menuPoint) {
		expect(menuPoint.patchAddr).toEqual(
			pythonResult.patchPoints.menu.patchAddr
		);
		expect(menuPoint.originalBytes).toEqual(
			pythonResult.patchPoints.menu.originalBytes
		);
		expect(menuPoint.newBytes).toEqual(
			pythonResult.patchPoints.menu.newBytes
		);
	}
}

describe('Theme Patcher - Instruction Encoding', () => {
	describe('encodeBl', () => {
		it('should encode forward BL instruction correctly', () => {
			const fromAddr = 0x1000;
			const toAddr = 0x2000;

			const blBytes = encodeBl(fromAddr, toAddr);

			// Verify it's a valid BL instruction
			const hw1 = blBytes[0] | (blBytes[1] << 8);
			const hw2 = blBytes[2] | (blBytes[3] << 8);

			expect(hw1 & 0xf800).toEqual(0xf000);
			expect(hw2 & 0xd000).toEqual(0xd000);
		});

		it('should encode backward BL instruction correctly', () => {
			const fromAddr = 0x2000;
			const toAddr = 0x1000;

			const blBytes = encodeBl(fromAddr, toAddr);

			const hw1 = blBytes[0] | (blBytes[1] << 8);
			const hw2 = blBytes[2] | (blBytes[3] << 8);

			expect(hw1 & 0xf800).toEqual(0xf000);
			expect(hw2 & 0xd000).toEqual(0xd000);
		});

		it('should maintain BL roundtrip correctness', () => {
			const fromAddr = 0x86cb0;
			const toAddr = 0xa0f3a0;

			const blBytes = encodeBl(fromAddr, toAddr);

			// Decode and verify using the same formula as Python
			const hw1 = blBytes[0] | (blBytes[1] << 8);
			const hw2 = blBytes[2] | (blBytes[3] << 8);

			const S = (hw1 >> 10) & 1;
			const imm10 = hw1 & 0x7ff;  // Extract 11 bits (not 10!)
			const J1 = (hw2 >> 13) & 1;
			const J2 = (hw2 >> 11) & 1;
			const imm11 = hw2 & 0x7ff;

			const I1 = ~(J1 ^ S) & 1;
			const I2 = ~(J2 ^ S) & 1;

			// Reconstruct: S:I1:I2:imm10:imm11
			// Note: imm10 is placed at bits [21:11] in the reconstruction
			const imm25 = (S << 24) | (I1 << 23) | (I2 << 22) | (imm10 << 11) | imm11;
			let imm32 = imm25 << 1;
			if (S) {
				imm32 |= 0xfe000000;
			}

			// Convert to signed 32-bit
			if (imm32 & 0x80000000) {
				imm32 = imm32 - 0x100000000;
			}

			const decodedTarget = (fromAddr + 4 + imm32) >>> 0;

			expect(decodedTarget).toEqual(toAddr);
		});

		it('should reject BL offsets out of range', () => {
			const fromAddr = 0x100000;

			// More than +16MB
			expect(() => encodeBl(fromAddr, fromAddr + 0x1000004)).toThrow();
		});
	});

	describe('encodeB16bit', () => {
		it('should encode 16-bit B instruction correctly', () => {
			const fromAddr = 0x1000;
			const toAddr = 0x1000 + 0x802; // Near max forward

			const bBytes = encodeB16bit(fromAddr, toAddr);

			expect(bBytes.length).toEqual(2);
		});

		it('should reject B offsets out of range', () => {
			const fromAddr = 0x1000;

			expect(() => encodeB16bit(fromAddr, fromAddr + 0x1000)).toThrow();
		});
	});

	describe('encodeMovw', () => {
		it('should encode MOVW instruction correctly', () => {
			const reg = 5;
			const imm16 = 0xf800;

			const movwBytes = encodeMovw(reg, imm16);

			// Verify encoding
			const hw1 = movwBytes[0] | (movwBytes[1] << 8);
			const hw2 = movwBytes[2] | (movwBytes[3] << 8);

			expect(hw1 & 0xfbf0).toEqual(0xf240);
			expect((hw2 >> 8) & 0xf).toEqual(reg);
		});
	});

	describe('encodePush', () => {
		it('should encode PUSH instruction correctly', () => {
			const regs = [0, 1, 2, 14]; // R0, R1, R2, LR

			const pushBytes = encodePush(regs);

			expect(pushBytes.length).toEqual(3);
		});
	});
});

describe('Theme Patcher - Function Discovery', () => {
	// These tests require actual firmware data
	// In CI/CD, the firmware should be downloaded first

	const testFirmwarePath = 'references/HIFIEC10.IMG';

	it('should discover FLAC function', () => {
		const firmwareData = fileIO.readFileSync(testFirmwarePath);
		const result = discoverFlacFunction(firmwareData);

		expect(result).not.toBeNull();
		if (result) {
			const [funcAddr, patchAddr] = result;
			expect(funcAddr).toBeGreaterThan(0);
			expect(patchAddr).toBeGreaterThan(0);

			// Verify pattern at patch address
			expect(firmwareData[patchAddr]).toEqual(0x04);
			expect(firmwareData[patchAddr + 1]).toEqual(0x29);
			expect(firmwareData[patchAddr + 2]).toEqual(0x0c);
			expect(firmwareData[patchAddr + 3]).toEqual(0xbf);
		}
	});

	it('should discover Menu function', () => {
		const firmwareData = fileIO.readFileSync(testFirmwarePath);
		const result = discoverMenuFunction(firmwareData);

		expect(result).not.toBeNull();
		if (result) {
			const [funcAddr, patchAddr] = result;
			expect(funcAddr).toBeGreaterThan(0);
			expect(patchAddr).toBeGreaterThan(0);

			// Verify pattern at patch address
			expect(firmwareData[patchAddr]).toEqual(0x4f);
			expect(firmwareData[patchAddr + 1]).toEqual(0xf0);
			expect(firmwareData[patchAddr + 2]).toEqual(0x00);
			expect(firmwareData[patchAddr + 3]).toEqual(0x0c);
		}
	});

	it('should find function start', () => {
		const firmwareData = fileIO.readFileSync(testFirmwarePath);
		const addr = 0x86cb0;
		const funcStart = findFunctionStart(firmwareData, addr);

		expect(funcStart).toBeGreaterThan(0);
		expect(funcStart).toBeLessThanOrEqual(addr);
	});
});

describe('Theme Patcher - NOP Slide Finder', () => {
	it('should find valid NOP slides', () => {
		const firmwareData = fileIO.readFileSync('references/HIFIEC10.IMG');
		const finder = new NopSlideFinder(firmwareData);
		const slides = finder.findAllSlides();

		expect(slides.length).toBeGreaterThan(0);

		for (const slide of slides) {
			expect(slide.size).toBeGreaterThan(0);
			expect(slide.end).toBeGreaterThan(slide.start);
		}
	});

	it('should select best NOP slide', () => {
		const firmwareData = fileIO.readFileSync('references/HIFIEC10.IMG');
		const finder = new NopSlideFinder(firmwareData);
		const funcAddrs = [0x86cb0, 0x3f870];

		const best = finder.selectBestSlide(funcAddrs, 250);

		expect(best).not.toBeNull();
		if (best) {
			expect(best.size).toBeGreaterThanOrEqual(250);

			// Check distance is within BL range
			for (const funcAddr of funcAddrs) {
				const distance = Math.abs(best.start - funcAddr);
				expect(distance).toBeLessThanOrEqual(16777216);
			}
		}
	});
});

describe('Theme Patcher - Patch Detection', () => {
	const firmwareData = fileIO.readFileSync('references/HIFIEC10.IMG');

	it('should detect original firmware as not patched', () => {
		const detector = new PatchDetector(firmwareData, 'Unknown');
		const flacResult = discoverFlacFunction(firmwareData);

		if (flacResult) {
			const [funcAddr] = flacResult;
			const [isPatched, status] = detector.detectFlacPatch(funcAddr);
			expect(isPatched).toBe(false);
			expect(status).toContain('Original');
		}
	});

	it('should check if instruction is BL', () => {
		const detector = new PatchDetector(firmwareData);

		// At a known non-BL instruction
		expect(detector.isBlInstruction(0x86cb0)).toBe(false);
	});

	it('should read patch metadata', () => {
		const finder = new NopSlideFinder(firmwareData);
		const slides = finder.findAllSlides();

		if (slides.length > 0) {
			const detector = new PatchDetector(firmwareData);
			const metadata = detector.readPatchMetadata(slides[0]);

			// Original firmware should not have metadata
			expect(metadata).toBeNull();
		}
	});
});

describe('Theme Patcher - CRC16', () => {
	it('should produce consistent CRC16 values', () => {
		const data = new Uint8Array([0x48, 0x65, 0x6c, 0x6c, 0x6f]); // "Hello"

		const crc1 = crc16(data);
		const crc2 = crc16(data);

		expect(crc1).toEqual(crc2);
	});

	it('should produce different CRC16 for different data', () => {
		const crc1 = crc16(new Uint8Array([0x01, 0x02]));
		const crc2 = crc16(new Uint8Array([0x01, 0x03]));

		expect(crc1).not.toEqual(crc2);
	});

	it('should handle empty data', () => {
		const crc = crc16(new Uint8Array([]));
		expect(typeof crc).toBe('number');
	});
});

describe('Theme Patcher - Full Patching Workflow', () => {
	it('should analyze firmware', () => {
		const firmwareData = fileIO.readFileSync('references/HIFIEC10.IMG');
		const patcher = new ThemePatcher(firmwareData);
		const result = patcher.analyze();

		expect(result.version).toBeTruthy();
		expect(result.themeFunctions.length).toBeGreaterThan(0);
		expect(result.nopSlides.length).toBeGreaterThan(0);
	});

	it('should patch firmware with custom colors', () => {
		const firmwareData = fileIO.readFileSync('references/HIFIEC10.IMG');
		const patcher = new ThemePatcher(firmwareData);

		const flacColors = [0xf800, 0x001f, 0xffe0, 0x07ff, 0x0000];
		const menuColors = [0xf800, 0xf800, 0xf800, 0x001f, 0x001f, 0x001f, 0xffe0, 0xffe0, 0xffe0, 0x07ff, 0x07ff, 0x07ff, 0x0000, 0x0000, 0x0000];

		const result = patcher.patch(flacColors, menuColors, '/tmp/test.IMG', true);

		expect(result.success).toBe(true);
		expect(result.nopSlide.start).toBeGreaterThan(0);
		expect(result.patchPoints).toBeDefined();
	});

	it('should reject invalid color counts', () => {
		const firmwareData = fileIO.readFileSync('references/HIFIEC10.IMG');
		const patcher = new ThemePatcher(firmwareData);

		// Too few FLAC colors
		expect(() =>
			patcher.patch([0xf800, 0x001f, 0xffe0], [0xf800, 0xf800, 0xf800], '/tmp/test.IMG', true)
		).toThrow();

		// Too many menu colors
		expect(() =>
			patcher.patch(
				[0xf800, 0xf800, 0xf800, 0xf800, 0xf800],
				Array.from({ length: 20 }, () => 0xf800),
				'/tmp/test.IMG',
				true
			)
		).toThrow();
	});
});

describe('Theme Patcher - Python Integration Tests', () => {
	/**
	 * These tests compare TypeScript output with Python reference output.
	 * To run these tests:
	 * 1. Run the Python script to generate reference outputs
	 * 2. Place the outputs in references/test-results/
	 * 3. Run these Vitest tests
	 */

	const testResultsDir = 'references/test-results';

	// Skip if test results don't exist
	const runPythonIntegrationTests = fileIO.existsSync(testResultsDir);

	describe.skipIf(!runPythonIntegrationTests)('Python comparison', () => {
		it('should match Python FLAC function discovery', () => {
			const firmwareData = fileIO.readFileSync('references/HIFIEC10.IMG');
			const tsResult = discoverFlacFunction(firmwareData);

			// Load Python reference
			const pythonResult: PythonTestResult = JSON.parse(
				readFileSync(`${testResultsDir}/flac_discovery.json`, 'utf-8')
			);

			expect(tsResult).not.toBeNull();
			if (tsResult) {
				expect(tsResult[0]).toEqual(pythonResult.patchPoints.flac?.patchAddr ?? 0);
			}
		});

		it('should match Python Menu function discovery', () => {
			const firmwareData = fileIO.readFileSync('references/HIFIEC10.IMG');
			const tsResult = discoverMenuFunction(firmwareData);

			// Load Python reference
			const pythonResult: PythonTestResult = JSON.parse(
				readFileSync(`${testResultsDir}/menu_discovery.json`, 'utf-8')
			);

			expect(tsResult).not.toBeNull();
			if (tsResult) {
				expect(tsResult[0]).toEqual(pythonResult.patchPoints.menu?.patchAddr ?? 0);
			}
		});

		it('should match Python patch output', () => {
			const firmwareData = fileIO.readFileSync('references/HIFIEC10.IMG');
			const patcher = new ThemePatcher(firmwareData);

			const flacColors = [0xf800, 0x001f, 0xffe0, 0x07ff, 0x0000];
			const menuColors = Array(15).fill(0xf800);

			const tsResult = patcher.patch(flacColors, menuColors, '/tmp/test.IMG', true);

			// Load Python reference
			const pythonResult: PythonTestResult = JSON.parse(
				readFileSync(`${testResultsDir}/patch_output.json`, 'utf-8')
			);

			compareWithPython(tsResult, pythonResult);
		});

		it('should match Python NOP slide selection', () => {
			const firmwareData = fileIO.readFileSync('references/HIFIEC10.IMG');
			const finder = new NopSlideFinder(firmwareData);
			const funcAddrs = [0x86cb0, 0x3f870];

			const tsSlide = finder.selectBestSlide(funcAddrs, 250);

			// Load Python reference
			const pythonResult: PythonTestResult = JSON.parse(
				readFileSync(`${testResultsDir}/nop_slide.json`, 'utf-8')
			);

			expect(tsSlide).not.toBeNull();
			if (tsSlide) {
				expect(tsSlide.start).toEqual(pythonResult.nopSlide.start);
				expect(tsSlide.end).toEqual(pythonResult.nopSlide.end);
				expect(tsSlide.size).toEqual(pythonResult.nopSlide.size);
			}
		});
	});
});

describe('Theme Patcher - Batch Firmware Testing', () => {
	/**
	 * Test across all firmware versions to ensure compatibility
	 */

	const firmwareFiles: FirmwareFile[] = [
		{ version: 'V2.9.0', path: 'firmware/V2.9.0/HIFIEC10.IMG' },
		{ version: 'V3.0.0', path: 'firmware/V3.0.0/HIFIEC10.IMG' },
		{ version: 'V3.1.0', path: 'firmware/V3.1.0/HIFIEC10.IMG' }
	];

	// Skip if firmware files don't exist
	const runBatchTests = firmwareFiles.every((f) => fileIO.existsSync(f.path));

	describe.skipIf(!runBatchTests)('All firmware versions', () => {
		firmwareFiles.forEach(({ version, path }) => {
			describe(`Firmware ${version}`, () => {
				it('should discover theme functions', () => {
					const firmwareData = fileIO.readFileSync(path);
					const flacResult = discoverFlacFunction(firmwareData);
					const menuResult = discoverMenuFunction(firmwareData);

					expect(flacResult).not.toBeNull();
					expect(menuResult).not.toBeNull();
				});

				it('should analyze firmware', () => {
					const firmwareData = fileIO.readFileSync(path);
					const patcher = new ThemePatcher(firmwareData);
					const result = patcher.analyze();

					expect(result.canPatch).toBe(true);
					expect(result.themeFunctions.length).toBeGreaterThan(0);
				});

				it('should patch firmware', () => {
					const firmwareData = fileIO.readFileSync(path);
					const patcher = new ThemePatcher(firmwareData);

					const flacColors = [0xf800, 0x001f, 0xffe0, 0x07ff, 0x0000];
					const menuColors = Array(15).fill(0xf800);

					const result = patcher.patch(flacColors, menuColors, `/tmp/${version}.patched.IMG`, true);

					expect(result.success).toBe(true);
				});
			});
		});
	});
});
