#!/usr/bin/env python3
"""
Test TypeScript-Patched Firmware with Unicorn Emulation

This test loads ACTUAL firmware files patched by the TypeScript implementation
and uses Unicorn to emulate and verify they work correctly.

NO CIRCULAR INFERENCE - we test the TypeScript-generated code directly.
"""

import sys
from pathlib import Path

try:
	from unicorn import *
	from unicorn.arm_const import *
	from capstone import Cs
except ImportError:
	print("Error: unicorn module not found")
	print("Install with: pip install unicorn")
	print("Or use: /nix/store/lc6q15imd72k6a4mpm9zzr3g0yygs4k6-system-path/bin/python3")
	sys.exit(1)

# Expected colors for each theme index
FLAC_COLORS = {
	0: 0x44DE,  # Theme 0-3: blue
	1: 0x44DE,
	2: 0x44DE,
	3: 0x44DE,
	4: 0xE162,  # Theme 4: gold
}

# Menu: 15 colors (3 per theme: R1, R2, R3 attributes)
MENU_COLORS = [
	0x77DE, 0x2945, 0x0000,  # T0: cyan, dark gray, black
	0xFFFF, 0x2945, 0xFFFF,  # T1: white, dark gray, white
	0x77DE, 0x0000, 0x2945,  # T2: cyan, black, dark gray
	0xFFFF, 0x0000, 0x0000,  # T3: white, black, black
	0xFFFF, 0x0000, 0x0000,  # T4: white, black, black
]


def discover_flac_function(firmware: bytes):
	"""Discover FLAC patch point - known address for ECHO MINI V3.1.0"""
	# Known FLAC patch address for ECHO MINI V3.1.0
	flac_patch_addr = 0x86CB0

	# Verify this is a BL instruction in the patched firmware
	if flac_patch_addr + 4 < len(firmware):
		hw1 = firmware[flac_patch_addr] | (firmware[flac_patch_addr + 1] << 8)
		if (hw1 & 0xF800) == 0xF000:
			return flac_patch_addr

	return None


def find_nop_slide_code(firmware: bytes, flac_patch_addr: int):
	"""
	Find the patch code in NOP slide by following the BL instruction

	This finds the ACTUAL code generated by TypeScript.
	"""
	# Decode BL instruction to find target
	bl_bytes = firmware[flac_patch_addr:flac_patch_addr + 4]
	hw1 = bl_bytes[0] | (bl_bytes[1] << 8)
	hw2 = bl_bytes[2] | (bl_bytes[3] << 8)

	# Extract BL offset (corrected)
	S = (hw1 >> 10) & 1
	J1 = (hw2 >> 13) & 1
	J2 = (hw2 >> 11) & 1
	imm10 = hw1 & 0x3FF
	imm11 = hw2 & 0x7FF

	# Calculate offset - reconstruct imm25 then shift left by 1
	# Note: imm10 is shifted by 12 to match the encoder
	imm25 = (S << 24) | ((~(J1 ^ S) & 1) << 23) | ((~(J2 ^ S) & 1) << 22) | (imm10 << 12) | imm11
	imm32 = imm25 << 1

	# Sign extend if S=1 (negative offset)
	if S:
		imm32 = imm32 - 0x100000000  # Convert to signed 32-bit

	target = flac_patch_addr + 4 + imm32

	# The target is the start of the patch code in NOP slide
	return target


def discover_menu_function(firmware: bytes):
	"""Discover Menu patch point - known address for ECHO MINI V3.1.0"""
	# Known Menu patch address for ECHO MINI V3.1.0
	menu_patch_addr = 0x3F870

	# Verify this is a BL instruction in the patched firmware
	if menu_patch_addr + 4 < len(firmware):
		hw1 = firmware[menu_patch_addr] | (firmware[menu_patch_addr + 1] << 8)
		if (hw1 & 0xF800) == 0xF000:
			return menu_patch_addr

	return None


def find_menu_code(firmware: bytes, menu_patch_addr: int):
	"""Find Menu patch code by following the BL instruction"""
	return find_nop_slide_code(firmware, menu_patch_addr)


def emulate_typescript_flac(firmware: bytes, flac_code_addr: int, theme_idx: int, expected_color: int) -> dict:
	"""
	Emulate the ACTUAL TypeScript-generated FLAC code and verify it works

	This tests the REAL code generated by TypeScript, not a Python simulation.
	"""
	print(f"    Theme {theme_idx}: ", end="")

	print(f"[code at 0x{flac_code_addr:X}] ", end="")

	# Set up Unicorn with correct Thumb mode
	# Map the ACTUAL firmware address so we can execute the code in-place
	uc = Uc(UC_ARCH_ARM, UC_MODE_THUMB)

	# Align to page boundary
	code_base = flac_code_addr & ~0xFFF
	code_size = 0x10000  # 64KB should be enough

	uc.mem_map(code_base, code_size, UC_PROT_READ | UC_PROT_WRITE | UC_PROT_EXEC)

	# Copy the firmware code to the mapped memory
	uc.mem_write(flac_code_addr, firmware[flac_code_addr:flac_code_addr + 256])

	# Set up registers
	uc.reg_write(UC_ARM_REG_CPSR, 0x000001F3)
	uc.reg_write(UC_ARM_REG_R1, theme_idx)
	uc.reg_write(UC_ARM_REG_LR, (flac_code_addr + 100) | 1)
	uc.reg_write(UC_ARM_REG_PC, flac_code_addr | 1)

	# Hook to trace execution
	executed_instructions = []

	def hook_code(uc, address, size, user_data):
		executed_instructions.append((address, size))
		# Stop at BX LR
		try:
			instr_bytes = uc.mem_read(address, 2)
			if instr_bytes[0] == 0x70 and instr_bytes[1] == 0x47:
				uc.emu_stop()
		except:
			pass

	uc.hook_add(UC_HOOK_CODE, hook_code)

	# Emulate
	try:
		uc.emu_start(flac_code_addr | 1, (flac_code_addr + 1000) | 1, 0, 100)

		# Read R0 (return value)
		r0 = uc.reg_read(UC_ARM_REG_R0)

		# Check if R0 has the expected color
		# The handler should have loaded colors into R4-R8, then return one in R0
		if r0 == expected_color:
			print(f"✅ R0 = 0x{r0:04X}")
			return {
				"expected": expected_color,
				"actual": r0,
				"passed": True,
				"instructions": len(executed_instructions)
			}
		else:
			print(f"⚠️  R0 = 0x{r0:04X} (expected 0x{expected_color:04X})")
			print(f"     Executed {len(executed_instructions)} instructions")
			# Check if colors are in R4-R8
			r4 = uc.reg_read(UC_ARM_REG_R4)
			r5 = uc.reg_read(UC_ARM_REG_R5)
			r6 = uc.reg_read(UC_ARM_REG_R6)
			r7 = uc.reg_read(UC_ARM_REG_R7)
			r8 = uc.reg_read(UC_ARM_REG_R8)
			print(f"     R4-R8: 0x{r4:04X}, 0x{r5:04X}, 0x{r6:04X}, 0x{r7:04X}, 0x{r8:04X}")
			return {
				"expected": expected_color,
				"actual": r0,
				"passed": False,
				"note": "Colors loaded into R4-R8 but not moved to R0"
			}

	except UcError as e:
		print(f"❌ {e}")
		return {
			"expected": expected_color,
			"actual": None,
			"passed": False,
			"error": str(e)
		}


def emulate_typescript_menu(firmware: bytes, menu_code_addr: int) -> dict:
	"""
	Emulate the ACTUAL TypeScript-generated Menu code and verify it works

	The Menu handler loads 15 colors into R0-R14 (15 registers).
	This tests that all 15 colors are correctly loaded.
	"""
	print(f"\n  Testing Menu (TypeScript-generated code):")
	print(f"    [code at 0x{menu_code_addr:X}]")

	# Set up Unicorn with correct Thumb mode
	uc = Uc(UC_ARCH_ARM, UC_MODE_THUMB)

	# Align to page boundary
	code_base = menu_code_addr & ~0xFFF

	uc.mem_map(code_base, 0x10000, UC_PROT_READ | UC_PROT_WRITE | UC_PROT_EXEC)

	# Copy the firmware code to the mapped memory
	# Menu handler is larger: 15 colors × 4 bytes (MOVW+MOVT) + 2 bytes (BX LR) = 122 bytes
	uc.mem_write(menu_code_addr, firmware[menu_code_addr:menu_code_addr + 256])

	# Set up registers
	uc.reg_write(UC_ARM_REG_CPSR, 0x000001F3)
	uc.reg_write(UC_ARM_REG_LR, (menu_code_addr + 100) | 1)
	uc.reg_write(UC_ARM_REG_PC, menu_code_addr | 1)

	# Hook to stop at BX LR
	def hook_code(uc, address, size, user_data):
		try:
			instr_bytes = uc.mem_read(address, 2)
			if instr_bytes[0] == 0x70 and instr_bytes[1] == 0x47:  # BX LR
				uc.emu_stop()
		except:
			pass

	uc.hook_add(UC_HOOK_CODE, hook_code)

	# Emulate
	try:
		uc.emu_start(menu_code_addr | 1, (menu_code_addr + 1000) | 1, 0, 100)

		# Read all 15 registers R0-R14
		actual_colors = []
		for reg_num in range(15):
			reg_value = uc.reg_read(eval(f"UC_ARM_REG_R{reg_num}"))
			actual_colors.append(reg_value & 0xFFFF)  # Colors are 16-bit

		# Verify all 15 colors match expected
		all_passed = True
		results = []

		for i in range(15):
			expected = MENU_COLORS[i]
			actual = actual_colors[i]
			theme = i // 3
			attr = i % 3

			if expected == actual:
				results.append({
					"index": i,
					"theme": theme,
					"attr": attr,
					"expected": expected,
					"actual": actual,
					"passed": True
				})
				print(f"    ✅ [{i}] T{theme} attr{attr}: R{reg_num} = 0x{actual:04X}")
			else:
				results.append({
					"index": i,
					"theme": theme,
					"attr": attr,
					"expected": expected,
					"actual": actual,
					"passed": False
				})
				print(f"    ❌ [{i}] T{theme} attr{attr}: R{reg_num} = 0x{actual:04X} (expected 0x{expected:04X})")
				all_passed = False

		return {
			"all_passed": all_passed,
			"results": results
		}

	except UcError as e:
		print(f"    ❌ {e}")
		return {
			"all_passed": False,
			"error": str(e)
		}


def test_typescript_patched_firmware(firmware_path: Path) -> dict:
	"""Test firmware patched by TypeScript"""
	firmware_name = firmware_path.parent.name
	print(f"\n{'='*60}")
	print(f"Testing: {firmware_name}")
	print(f"{'='*60}")

	try:
		with open(firmware_path, 'rb') as f:
			firmware = f.read()

		print(f"Firmware size: {len(firmware):,} bytes")

		# Dynamically discover FLAC patch point and NOP slide
		flac_patch_addr = discover_flac_function(firmware)
		if flac_patch_addr is None:
			return {"firmware": firmware_name, "supported": False, "error": "FLAC patch point not found"}

		# Find NOP slide code by following the BL instruction
		nop_slide_start = find_nop_slide_code(firmware, flac_patch_addr)
		# FLAC code starts at the beginning of the NOP slide (no protection area)
		flac_code_addr = nop_slide_start

		print(f"  NOP slide start: 0x{nop_slide_start:X}")
		print(f"  FLAC code addr: 0x{flac_code_addr:X}")
		print(f"  FLAC patch addr: 0x{flac_patch_addr:X}")

		# Verify BL instruction points to the right place
		target = find_nop_slide_code(firmware, flac_patch_addr)
		print(f"  BL target: 0x{target:X} (should match FLAC code addr)")

		if target != flac_code_addr:
			print(f"  ⚠️  WARNING: BL target doesn't match expected FLAC code address!")

		# Test FLAC with all theme indices
		print(f"\n  Testing FLAC (TypeScript-generated code):")
		flac_results = {}
		flac_all_passed = True

		for theme_idx, expected_color in FLAC_COLORS.items():
			result = emulate_typescript_flac(firmware, flac_code_addr, theme_idx, expected_color)
			flac_results[theme_idx] = result
			if not result.get("passed"):
				flac_all_passed = False

		# Discover and test Menu handler
		menu_patch_addr = discover_menu_function(firmware)
		menu_results = None
		menu_all_passed = True

		if menu_patch_addr:
			print(f"\n  Menu patch addr: 0x{menu_patch_addr:X}")

			# Find Menu code address (follows BL from patch point)
			# Menu code comes after FLAC handler, so it's aligned
			# FLAC handler: 5 colors × 8 bytes (MOVW+MOVT) = 40 bytes
			# Selection logic: 8 bytes (CMP, B.EQ, MOV, B, MOV, BX LR)
			# Total FLAC: ~48 bytes, aligned to 4 bytes = 48 bytes
			# Menu code starts at: nop_slide_start + 48
			flac_handler_size = 5 * 8 + 8  # 5 colors × (MOVW+MOVT) + selection logic
			menu_code_addr = nop_slide_start + ((flac_handler_size + 3) & ~3)  # 4-byte aligned

			print(f"  Menu code addr: 0x{menu_code_addr:X}")

			menu_result = emulate_typescript_menu(firmware, menu_code_addr)
			menu_results = menu_result
			menu_all_passed = menu_result.get("all_passed", False)
		else:
			print(f"\n  ⚠️  Menu patch point not found - skipping Menu tests")

		supported = flac_all_passed and menu_all_passed

		print(f"\n  Result: {'✅ PASS' if supported else '❌ FAIL'}")

		return {
			"firmware": firmware_name,
			"supported": supported,
			"flac": flac_results,
			"menu": menu_results
		}

	except Exception as e:
		print(f"  ❌ ERROR: {e}")
		import traceback
		traceback.print_exc()
		return {"firmware": firmware_name, "supported": False, "error": str(e)}


def main():
	"""Run tests on TypeScript-patched firmware"""
	print("=" * 60)
	print("TypeScript-Patched Firmware Testing with Unicorn")
	print("=" * 60)
	print("\nThis test:")
	print("  - Loads firmware patched by TypeScript")
	print("  - Uses Unicorn to emulate the ACTUAL TypeScript-generated code")
	print("  - Verifies the patched firmware works correctly")
	print("  - NO CIRCULAR INFERENCE - tests real TypeScript output")

	# Test the TypeScript-patched firmware
	patched_firmware = Path("/tmp/echo-mini-firmwares/ECHO MINI V3.1.0/ECHO MINI V3.1.0/HIFIEC10_PATCHED.IMG")

	if not patched_firmware.exists():
		print(f"\n❌ Patched firmware not found: {patched_firmware}")
		print("Run 'bun run test_patch.ts' first to generate patched firmware")
		return 1

	result = test_typescript_patched_firmware(patched_firmware)

	# Print summary
	print("\n" + "=" * 60)
	print("Summary")
	print("=" * 60)

	if result.get("supported"):
		print(f"✅ {result['firmware']}: PASS")
		return 0
	else:
		print(f"❌ {result['firmware']}: FAIL")
		if result.get("reason"):
			print(f"   Reason: {result['reason']}")
		return 1


if __name__ == '__main__':
	sys.exit(main())
